// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct RpsArenaClientProgram;
impl sails_rs::client::Program for RpsArenaClientProgram {}
pub trait RpsArenaClient {
    type Env: sails_rs::client::GearEnv;
    fn rps(&self) -> sails_rs::client::Service<rps::RpsImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> RpsArenaClient
    for sails_rs::client::Actor<RpsArenaClientProgram, E>
{
    type Env = E;
    fn rps(&self) -> sails_rs::client::Service<rps::RpsImpl, Self::Env> {
        self.service(stringify!(Rps))
    }
}
pub trait RpsArenaClientCtors {
    type Env: sails_rs::client::GearEnv;
    /// Constructor: set reveal timeout in blocks (e.g., 100 blocks ≈ 5 minutes on Vara)
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        reveal_timeout: u32,
    ) -> sails_rs::client::PendingCtor<RpsArenaClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> RpsArenaClientCtors
    for sails_rs::client::Deployment<RpsArenaClientProgram, E>
{
    type Env = E;
    fn new(
        self,
        reveal_timeout: u32,
    ) -> sails_rs::client::PendingCtor<RpsArenaClientProgram, io::New, Self::Env> {
        self.pending_ctor((reveal_timeout,))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (reveal_timeout: u32) -> ());
}

pub mod rps {
    use super::*;
    pub trait Rps {
        type Env: sails_rs::client::GearEnv;
        /// Cancel a game you created that hasn't been joined yet.
        fn cancel_game(
            &mut self,
            game_id: u64,
        ) -> sails_rs::client::PendingCall<io::CancelGame, Self::Env>;
        /// Claim win if opponent didn't reveal in time.
        fn claim_timeout(
            &mut self,
            game_id: u64,
        ) -> sails_rs::client::PendingCall<io::ClaimTimeout, Self::Env>;
        /// Create a new game with your committed move hash.
        /// Commitment = simple_hash(SCALE(move) ++ salt_bytes).
        /// Use the query ComputeCommitment to generate your commitment.
        fn create_game(
            &mut self,
            commitment: H256,
        ) -> sails_rs::client::PendingCall<io::CreateGame, Self::Env>;
        /// Join an existing game with your committed move hash.
        fn join_game(
            &mut self,
            game_id: u64,
            commitment: H256,
        ) -> sails_rs::client::PendingCall<io::JoinGame, Self::Env>;
        /// Reveal your move and salt. Contract verifies commitment.
        fn reveal(
            &mut self,
            game_id: u64,
            mv: Move,
            salt: String,
        ) -> sails_rs::client::PendingCall<io::Reveal, Self::Env>;
        /// Helper: compute a commitment hash for a move and salt.
        /// Use this query to generate your commitment before creating/joining a game.
        fn compute_commitment(
            &self,
            mv: Move,
            salt: String,
        ) -> sails_rs::client::PendingCall<io::ComputeCommitment, Self::Env>;
        /// Get info about a specific game.
        fn game_state(
            &self,
            game_id: u64,
        ) -> sails_rs::client::PendingCall<io::GameState, Self::Env>;
        /// Get the leaderboard sorted by wins.
        fn leaderboard(&self) -> sails_rs::client::PendingCall<io::Leaderboard, Self::Env>;
        /// List games for a specific player.
        fn my_games(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::MyGames, Self::Env>;
        /// List games waiting for an opponent.
        fn open_games(&self) -> sails_rs::client::PendingCall<io::OpenGames, Self::Env>;
    }
    pub struct RpsImpl;
    impl<E: sails_rs::client::GearEnv> Rps for sails_rs::client::Service<RpsImpl, E> {
        type Env = E;
        fn cancel_game(
            &mut self,
            game_id: u64,
        ) -> sails_rs::client::PendingCall<io::CancelGame, Self::Env> {
            self.pending_call((game_id,))
        }
        fn claim_timeout(
            &mut self,
            game_id: u64,
        ) -> sails_rs::client::PendingCall<io::ClaimTimeout, Self::Env> {
            self.pending_call((game_id,))
        }
        fn create_game(
            &mut self,
            commitment: H256,
        ) -> sails_rs::client::PendingCall<io::CreateGame, Self::Env> {
            self.pending_call((commitment,))
        }
        fn join_game(
            &mut self,
            game_id: u64,
            commitment: H256,
        ) -> sails_rs::client::PendingCall<io::JoinGame, Self::Env> {
            self.pending_call((game_id, commitment))
        }
        fn reveal(
            &mut self,
            game_id: u64,
            mv: Move,
            salt: String,
        ) -> sails_rs::client::PendingCall<io::Reveal, Self::Env> {
            self.pending_call((game_id, mv, salt))
        }
        fn compute_commitment(
            &self,
            mv: Move,
            salt: String,
        ) -> sails_rs::client::PendingCall<io::ComputeCommitment, Self::Env> {
            self.pending_call((mv, salt))
        }
        fn game_state(
            &self,
            game_id: u64,
        ) -> sails_rs::client::PendingCall<io::GameState, Self::Env> {
            self.pending_call((game_id,))
        }
        fn leaderboard(&self) -> sails_rs::client::PendingCall<io::Leaderboard, Self::Env> {
            self.pending_call(())
        }
        fn my_games(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::MyGames, Self::Env> {
            self.pending_call((player,))
        }
        fn open_games(&self) -> sails_rs::client::PendingCall<io::OpenGames, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(CancelGame (game_id: u64) -> ());
        sails_rs::io_struct_impl!(ClaimTimeout (game_id: u64) -> ());
        sails_rs::io_struct_impl!(CreateGame (commitment: H256) -> u64);
        sails_rs::io_struct_impl!(JoinGame (game_id: u64, commitment: H256) -> ());
        sails_rs::io_struct_impl!(Reveal (game_id: u64, mv: super::Move, salt: String) -> ());
        sails_rs::io_struct_impl!(ComputeCommitment (mv: super::Move, salt: String) -> H256);
        sails_rs::io_struct_impl!(GameState (game_id: u64) -> Option<super::GameInfo>);
        sails_rs::io_struct_impl!(Leaderboard () -> Vec<(ActorId,super::PlayerStats,)>);
        sails_rs::io_struct_impl!(MyGames (player: ActorId) -> Vec<super::GameInfo>);
        sails_rs::io_struct_impl!(OpenGames () -> Vec<super::GameInfo>);
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Move {
    Rock,
    Paper,
    Scissors,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct GameInfo {
    pub id: u64,
    pub creator: ActorId,
    pub opponent: Option<ActorId>,
    pub status: GameStatus,
    pub creator_commitment: H256,
    pub opponent_commitment: Option<H256>,
    pub creator_move: Option<Move>,
    pub opponent_move: Option<Move>,
    pub winner: Option<ActorId>,
    pub result: Option<GameResult>,
    pub created_at_block: u32,
    pub committed_at_block: Option<u32>,
    pub reveal_deadline_blocks: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum GameStatus {
    WaitingForOpponent,
    BothCommitted,
    Settled,
    Cancelled,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum GameResult {
    Win,
    Lose,
    Draw,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct PlayerStats {
    pub wins: u32,
    pub losses: u32,
    pub draws: u32,
    pub games_played: u32,
}
